# pvc-demo.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  storageClassName: pd-example
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Gi

